@ECHO OFF

REM -------------------------------
REM     COPYFILES.BAT
REM -------------------------------

COPY Z:\WINPENTE\v2.0\RELEASE\WINPENTE.EXE C:\PUBLIC\SHARED\WINPENTE
COPY Z:\WINPENTE\v2.0\RESDLL\RELEASE\WPRES32.DLL C:\PUBLIC\SHARED\WINPENTE
COPY Z:\WINPENTE\v2.0\THINK\RELEASE\WPTHK32.DLL C:\PUBLIC\SHARED\WINPENTE
