//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Northwind.rc
//
#define IDD_FAMILYINFO                  101
#define IDB_FILEOPEN                    102
#define ID_FILE_EXIT                    102
#define IDB_BITMAP1                     103
#define ID_HELP_ABOUT                   103
#define ID_VIEW_CATEGORIES              106
#define ID_VIEW_CUSTOMERS               107
#define ID_VIEW_EMPLOYEES               108
#define ID_VIEW_ORDERDETAILS            109
#define ID_VIEW_ORDERS                  110
#define ID_VIEW_PRODUCTS                111
#define IDD_ABOUT                       112
#define ID_VIEW_SHIPPERS                112
#define ID_VIEW_SUPPLIERS               113
#define ID_REPORTS_SALESBYYEAR          114
#define ID_REPORTS_SALESBYCATEGORY      115
#define ID_REPORTS_CUSTOMERSANDSUPPLIERSBYCITY 116
#define ID_REPORTS_EMPLOYEESALESBYCOUNTRY 117
#define IDR_TOOLBAR1                    118
#define ID_FILE_PRINT                   118
#define ID_CUSTDLG                      122
#define ID_CATDLG                       123
#define ID_EMPDLG                       124
#define ID_ORDDETDLG                    125
#define ID_ORDERSDLG                    126
#define ID_PRODUCTSDLG                  127
#define ID_SHIPPERSDLG                  128
#define ID_SUPPLIERSDLG                 130
#define IDC_AGE                         1000
#define IDC_DOBCAP                      1001
#define IDC_DOB                         1002
#define IDC_CREDITS                     1004
#define IDC_LINE                        1005
#define IDC_SYSRESCAP                   1006
#define IDC_SYSTEMRESOURCES             1007
#define IDC_EDCONNAME                   1012
#define IDC_STCONTITLE                  1013
#define IDC_EDCONTITLE                  1014
#define IDC_STADDRESS                   1015
#define IDC_EDADDRESS                   1016
#define IDC_STCITY                      1017
#define IDC_EDCITY                      1018
#define IDC_STREGION                    1019
#define IDC_EDREGION                    1020
#define IDC_STPOSTCODE                  1021
#define IDC_EDPOSTCODE                  1022
#define IDC_STCOUNTRY                   1023
#define IDC_EDCOUNTRY                   1024
#define IDC_STPHONE                     1025
#define IDC_EDPHONE                     1026
#define IDC_STFAX                       1027
#define IDC_EDFAX                       1028
#define IDC_EDCATNAME                   1029
#define IDC_STCATDESC                   1030
#define IDC_EDCATDESC                   1031
#define IDC_STFIRSTNAME                 1032
#define IDC_STTITLE                     1033
#define IDC_STTOC                       1034
#define IDC_STBIRTHDATE                 1035
#define IDC_STHIREDATE                  1036
#define IDC_STPOSTALCODE                1037
#define IDC_STHOMEPHONE                 1038
#define IDC_STEXTENSION                 1039
#define IDC_STREPORTSTO                 1040
#define IDC_STNOTES                     1041
#define IDC_EDNOTES                     1042
#define IDC_EDLASTNAME                  1043
#define IDC_EDFIRSTNAME                 1044
#define IDC_EDTITLE                     1045
#define IDC_EDTOC                       1046
#define IDC_EDBIRTHDATE                 1047
#define IDC_EDHIREDATE                  1049
#define IDC_EDPOSTALCODE                1053
#define IDC_EDHOMEPHONE                 1055
#define IDC_EDEXTENSION                 1056
#define IDC_EDREPORTSTO                 1057
#define IDC_EDORDERID                   1058
#define IDC_EDPRODUCTID                 1059
#define IDC_EDUNITPRICE                 1060
#define IDC_EDQUANTITY                  1061
#define IDC_EDDISCOUNT                  1062
#define IDC_STORDERID                   1063
#define IDC_STPRODUCTID                 1064
#define IDC_STUNITPRICE                 1065
#define IDC_STQUANTITY                  1066
#define IDC_EDCUSTID                    1067
#define IDC_EDEMPID                     1068
#define IDC_STEMPID                     1069
#define IDC_EDORDDATE                   1070
#define IDC_EDREQDATE                   1071
#define IDC_EDSHIPDATE                  1072
#define IDC_EDSHIPVIA                   1073
#define IDC_STORDDATE                   1074
#define IDC_STREQDATE                   1075
#define IDC_STSHIPDATE                  1076
#define IDC_STSHIPVIA                   1077
#define IDC_EDFREIGHT                   1078
#define IDC_STFREIGHT                   1079
#define IDC_STSHIPNAME                  1080
#define IDC_EDSHIPNAME                  1081
#define IDC_FMSEPERATOR                 1082
#define IDC_EDSHIPADDRESS               1083
#define IDC_STSHIPADDRESS               1084
#define IDC_EDSHIPCITY                  1085
#define IDC_STSHIPCITY                  1086
#define IDC_EDSHIPREGION                1087
#define IDC_STSHIPREGION                1088
#define IDC_EDSHIPPOSTAL                1089
#define IDC_STSHIPPOSTAL                1090
#define IDC_EDSHIPCOUNTRY               1091
#define IDC_STSHIPCOUNTRY               1092
#define IDC_EDPRODUCTNAME               1093
#define IDC_STSUPPLIER                  1094
#define IDC_EDSUPPLIER                  1095
#define IDC_STCATEGORY                  1096
#define IDC_EDCATEGORY                  1097
#define IDC_STQUANTITYPERUNIT           1098
#define IDC_EDQUANTITYPERUNIT           1099
#define IDC_STUNITSINSTOCK              1101
#define IDC_EDUNITSINSTOCK              1102
#define IDC_STUNITSONORDER              1103
#define IDC_EDUNITSONORDER              1104
#define IDC_STREORDERLEVEL              1105
#define IDC_EDREORDERLEVEL              1106
#define IDC_STDISCONTINUED              1107
#define IDC_EDDISCONTINUED              1108
#define IDC_EDCOMPNAME                  1111
#define IDC_AGECAP                      -1
#define IDC_PLANET                      -1
#define IDC_STCONNAME                   -1
#define IDC_STCATNAME                   -1
#define IDC_STLASTNAME                  -1
#define IDC_STDISCOUNT                  -1
#define IDC_STCUSTID                    -1
#define IDC_STPRODUCTNAME               -1
#define IDC_STCOMPANYNAME               -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         126
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
