#ifndef __guiPropertiesDlg__
#define __guiPropertiesDlg__

/**
@file
Subclass of PropertiesDlg, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing PropertiesDlg */
class guiPropertiesDlg : public PropertiesDlg
{
public:
	/** Constructor */
	guiPropertiesDlg( wxWindow* parent );
};

#endif // __guiPropertiesDlg__
