#ifndef __guiPropertiesDlg__
#define __guiPropertiesDlg__

/**
@file
Subclass of PropertiesDlg, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing PropertiesDlg */
class guiPropertiesDlg : public PropertiesDlg {
public:
	/** Constructor */
	guiPropertiesDlg(wxWindow* parent, iso9660_stat_t *stat);

private:
	iso9660_stat_t *m_stat;
};

#endif // __guiPropertiesDlg__
