/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

#define WXCDIO_APP_NAME	_T("wxCDIO")

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp {
public:
	MainApp();

	bool OnInit();
	int OnExit(void);

	wxFrame *GetFrame() const;

	DECLARE_EVENT_TABLE()

private:
	void OnUpdateVolInfo(wxUpdateUIEvent &event);
	wxDocManager* m_docManager;
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

#endif //__main__
